name: boilerplate_rivepod_flutter
description: "A production-ready Flutter project boilerplate with Riverpod, GoRouter, and modern architecture patterns."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.2.0

  # Environment & Configuration
  flutter_dotenv: ^5.1.0

  # Localization
  easy_localization: ^3.0.3

  # Network & API
  dio: ^5.4.0
  encrypt: ^5.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5

  # Code Generation
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # UI & Utilities
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  intl: ^0.20.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  hive_generator: ^2.0.1

  # Analysis & Linting
  very_good_analysis: ^5.1.0
  custom_lint: ^0.6.0

  # Testing
  mockito: ^5.4.4
  build_test: ^2.2.0
  integration_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  alchemist: ^0.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/translations/
    - .env

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/Inter-Bold.ttf
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
